### ISSUE TITLE
As a custom config provider for cpptools, notifyReady is invoked twice on start

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cmake-tools#1072]
I'm seeing multiple calls to notifyReady() in cpptools API, from CMake Tools, on start up (when opening a folder).

The code is in extension.ts: `_updateCodeModel` line 485.  

notifyReady() should probably only be invoked once, and didChangeCustomConfiguration() used for subsequent changes. Though, it should probably also only deliver a configuration once on startup - the second one seems to be redundant.

Might be related to using `cmake.configureOnOpen`

**Comment by bobbrow** [comment]
This should be addressed in the linked PR.

**Comment by Colengms** [comment]
The first call appears to be in response to a onCodeModelChanged notification, fired by getCMakeDriverInstance().

The next appears to be in response to a call to _updateCodeModel() from _postWorkspaceOpen().

**Comment by bobbrow** [comment]
I think this is fixed, but I'm not sure which PR added the check for multiple folders.  @Colengms do you still see this?

**Comment by Colengms** [comment]
We're still seeing 3 browse configurations on start-up (with configureOnOpen disabled, so not including one we would get when configuring).  Since we cache a browse config, this means cpptools will update the browse configuration 4 times on startup.

It looks like `updateCodeModel` in CMake Tools is being called 3 times on startup (possibly in parallel?).  The first time, it calls `notifyReady`, and the next 2 times it calls `didChangeCustomBrowseConfiguration`.  So, while it's not still calling `notifyReady` redundantly, it's still causing some redundant work on startup.

**Comment by sean-mcmanus** [comment]
...and with 2 workspace folders in the workspace that equals 8 browse configurations.
