### ISSUE TITLE
Unable to debug a target in Mac M1 BigSur

### ISSUE THREAD

**Issue by proton991** [microsoft/vscode-cmake-tools#2420]
```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
ERROR: Unable to start debugging. Unexpected LLDB output from command "-exec-run". process exited with status -1 (attach failed ((os[/kern]()) invalid argument))
The program '[/Users/***/Documents/Coding/c]()++[/PIC10B/build/cpptest]()' has exited with code 42 (0x0000002a).
```
I have already installed the CodeLLDB plugin and cmake build variant is Debug, but this error still exists. 

**lanuch.json**
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "clang++ ",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "C/C++: clang++"
        }
    ]
}

```

**task.json**
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: clang++",
			"command": "/usr/bin/clang++",
			"args": [
				"-g",
				"${file}",
				"-std=c++17",
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}"
			],
			"options": {
				"cwd": "${fileDirname}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "/usr/bin/clang++"
		}
	]
}

```

**Comment by bobbrow** [comment]
Are you on an M1 Mac?  Will this be resolved by: https://github.com/microsoft/vscode-cpptools/issues/7035?  We're hoping we can do a pre-release of cpptools this week with that issue resolved.  We're this close 🤏

**Comment by bobbrow** [comment]
> We're hoping we can do a pre-release of cpptools this week with that issue resolved. We're this close 🤏

Actually, we just released 1.9.3 of cpptools.  If you install this "pre-release" version and try again, do you still have the issue?

**Comment by proton991** [comment]
> > We're hoping we can do a pre-release of cpptools this week with that issue resolved. We're this close 🤏
> 
> Actually, we just released 1.9.3 of cpptools. If you install this "pre-release" version and try again, do you still have the issue?

I updated to 1.9.3 but sadly this error still exists.

**Comment by proton991** [comment]
I installed a x64 version cmake and use it to debug my code, it works. So this means that arm64 debugging natively is still not supported.
