### ISSUE TITLE
How to fix "Unable to determine what CMake generator to use"?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#908]
- **Operating System**:  Windows
- **CMake Version**: ?
- **VSCode Version**: 1.40.0
- **CMake Tools Extension Version**: 1.2.1
- **Compiler/Toolchain**:  Visual C++ 2019

I don't think this is a bug report, it's just a question on usage.

I have a working CMake project which, if I run from a Visual Studio 2017 developer command prompt, generates/builds fine. I don't have CMake or Ninja installed on my machine, except for what Visual Studio 2017 provides.

I can't generate/build the project using VS Code.  My top level CMakeLists.txt file is not in the root folder so, in VS Code User Settings, I have:

    "cmake.sourceDirectory": "${workspaceRoot}/CMake",
    "cmake.generator": "ninja",

I have selected a build kit:

![image](https://user-images.githubusercontent.com/7724321/68694205-a3c08280-0570-11ea-8ddf-12c6b05d8dc7.png)

The console window shows:

    [main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.

As I showed above, I have specified ninja as the generator, so I don't know why Tools is complaining about this.  Is it because I need to manually install CMake or Ninja?  Or should Tools provide these?  Or can I use the installations provided by VS 2017?

**Comment by bobbrow** [comment]
Hi @DavidA2014,

This is a bug which I believe should be addressed with #906.

**Comment by DavidA2014** [comment]
@bobbrow Thanks for your answer.

**Comment by bobbrow** [comment]
Please try version 1.2.2 (released today) and let us know if you are still having issues.  Thanks!

**Comment by DavidA2014** [comment]
@bobbrow Thanks for the update. I am still having issues. I now see:

    [cms-client] Configuring using the "ninja" CMake generator with plattform "undefined" and toolset {}
    [rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open [cmake-server] Failed to activate protocol version: Generator "ninja" not supported. {"folder":{"uri":{"$mid":1,"fsPath":"c:\\SVNProj\\zodiac\\branches\\TRY_TML_CMake_3Oct2019","_sep":1,"external":"file:///c%3A/SVNProj/zodiac/branches/TRY_TML_CMake_3Oct2019","path":"/c:/SVNProj/zodiac/branches/TRY_TML_CMake_3Oct2019","scheme":"file"},"name":"TRY_TML_CMake_3Oct2019","index":0}}

I guess the first message is related to #913?

The main issue seems to be:

    Failed to activate protocol version: Generator "ninja" not supported. 

I can run Ninja from a cmd prompt (it is in the system path). How can I fix this problem in Code?

**Comment by bobbrow** [comment]
Hi David,  I think I was able to reproduce your problem.  This might sound silly, but can you capitalize the first letter in "Ninja"?  It looks like CMake is case-sensitive...

```
D:\test\cmaketest2\build>cmake -G ninja ..
CMake Error: Could not create named generator ninja
```

I'll make a new issue about having the extension check the generator casing before sending it to CMake.

**Comment by DavidA2014** [comment]
@bobbrow I'm sorry, I should have spotted that. I have corrected the case and my project is now building nicely. Thanks very much for your help.
